[workspace]
members = [
    #     "bip32",
    #     "bip39",
    "cbor-util",
    "database",
    "kes",
    #     "ledger",
    #     "network",
    #     "vrf",
    #     "ledger/minicbor-derive",
    #     "ledger/sparse-struct",
    "plutus",
]

[workspace.dependencies]
# TODO: we don't need the half feature, only for debugging
minicbor = { version = "2.0", features = ["std", "half", "derive"] }
cbor-util = { path = "cbor-util" }

zerocopy = "0.8"
either = "1.15"
 
digest = "0.11.0-rc.2"
signature = { version = "3.0.0-rc.4", features = ["alloc"] }
 
blake2 = "0.11.0-rc.2"
# sha2 = "0.10"
# # TODO: Use the crates.io version once it's updated
# curve25519-dalek = { path = "../curve25519-dalek/curve25519-dalek", features = [
#     "digest",
# ] }
# # TODO: Use the crates.io version once it's updated
# ed25519-dalek = { path = "../curve25519-dalek/ed25519-dalek", features = [
#     "digest",
# ] }

[package]
name = "pallas-extras"
version = "0.1.0"
edition = "2024"

[dependencies]
# minicbor = { workspace = true }
# network = { path = "network" }
# ledger = { path = "ledger" }
# tokio = { version = "1", features = ["full"] }
# tokio-util = { version = "0.7", features = ["compat"] }
# futures = "0.3"
# const-hex = "1.14"
# sha2 = { version = "0.10", features = ["std"] }
# curve25519-dalek = { workspace = true }
# rand = "0.8"
# cbor-util = { path = "cbor-util" }
# indicatif = "0.17"
