[workspace]
members = [
    "bip32",
    "bip39",
    "cbor-util",
    "database",
    "kes",
    "ledger",
    #     "network",
    #     "vrf",
    #     "ledger/minicbor-derive",
    #     "ledger/sparse-struct",
    "plutus",
]

# TODO: We "default-features = false" on all crates.
[workspace.dependencies]
# TODO: Don't need half
minicbor = { version = "2.0", features = ["std", "half", "derive"] }
const-hex = { version = "1", default-features = false }
cbor-util = { path = "cbor-util" }

zerocopy = "0.8"
either = "1.15"
rand = "0.9"

# Crypto Traits
signature = { version = "=3.0.0-rc.4", default-features = false }
digest = { version = "0.11.0-rc.4", default-features = false }
 
# Hashing
blake2 = { version = "0.11.0-rc.3", default-features = false }
sha2 = { version = "0.11.0-rc.3", default-features = false }
sha3 = { version = "0.11.0-rc.3", default-features = false }

ed25519-dalek = { version = "3.0.0-pre.1", default-features = false }
curve25519-dalek = { version = "5.0.0-pre.1", default-features = false }

[package]
name = "pallas-extras"
version = "0.1.0"
edition = "2024"

[patch.crates-io]
# Be careful updating this dependency, some unsafe code depdends on its internal details.
# See code with `Safety:(blstrs)` comments.
blstrs = {  git = "https://github.com/carloskiki/blstrs" }

[dependencies]
