[package]
name = "kes"
version = "0.1.0"
edition = "2024"

[dependencies]
signature = { workspace = true, features = ["alloc"] }
blake2 = { workspace = true }
digest = { workspace = true }
either = { workspace = true }

ref-cast = { workspace = true }

[dev-dependencies]
ed25519-dalek = { workspace = true }
rand = { workspace = true }
