[package]
name = "kes"
version = "0.1.0"
edition = "2024"

[dependencies]
signature = { workspace = true, features = ["alloc"] }
blake2 = { workspace = true }
digest = { workspace = true }
either = { workspace = true }

ref-cast = "1.0"

[dev-dependencies]
ed25519-dalek = "3.0.0-pre.1"
rand = { workspace = true }
