[package]
name = "kes"
version = "0.1.0"
edition = "2024"

[dependencies]
signature = { workspace = true }
blake2 = { workspace = true }
digest = { workspace = true }
either = { workspace = true }
zerocopy = { workspace = true, features = ["derive"] }

[dev-dependencies]
ed25519-dalek = "3.0.0-pre.1"
rand = "0.10.0-rc.5"
