[package]
name = "bip39"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = { workspace = true }
const-hex = { workspace = true, features = ["alloc"] }

[dev-dependencies]
rand = { workspace = true }
