[package]
edition = "2024"
name = "bip39"
version = "0.1.0"

[dependencies]
const-hex = { workspace = true, features = ["alloc"] }
sha2 = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
