[package]
edition = "2024"
name = "network"
version = "0.1.0"

[dependencies]
cbor-util = { workspace = true }
minicbor = { workspace = true }
zerocopy = { workspace = true }

futures = "0.3"
ledger = { path = "../ledger" }

[[test]]
name = "mux"
