[package]
name = "cbor-util"
version = "0.1.0"
edition = "2024"

[dependencies]
signature = { workspace = true }
minicbor = { version = "2.1.3", features = ["full"] }

tinycbor = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
