[package]
name = "plutus"
version = "0.1.0"
edition = "2024"


[features]
test = []

[dependencies]
rug = { version = "1.28.0", default-features = false, features = ["integer", "std"] }

sha2 = { version = "0.11.0-rc.2", default-features = false, features = ["alloc"] }
sha3 = { version = "0.11.0-rc.3", default-features = false, features = ["alloc"] }
blake2 = "0.11.0-rc.2"
ed25519-dalek = { version = "3.0.0-pre.1", default-features = false, features = ["alloc"] }
k256 = "0.14.0-pre.11"
blstrs = "0.7" # TODO: Upgrade to 0.8 pre if possible
ripemd = "0.2.0-rc.1"

strum = { version = "0.27.2", features = ["derive"] }
macro_rules_attribute = "0.2.2"

const-hex = "1.16.0"
minicbor = { workspace = true }
cbor-util = { path = "../cbor-util" }

[dev-dependencies]
libtest2-mimic = "0.0.4"

[[test]]
name = "conformance"
harness = false
