[package]
name = "ledger"
version = "0.1.0"
edition = "2024"

[dependencies]
minicbor = { version = "2.1", features = ["full"] }
cbor-util = { workspace = true }
either = { workspace = true }
zerocopy = { workspace = true }

digest = { workspace = true }
ed25519-dalek = { workspace = true }
blake2 = { workspace = true }
sha3 = { workspace = true }
bech32 = "0.11"
crc32fast = "1.4"

kes = { path = "../kes" }
bip32 = { path = "../bip32" }
plutus = { path = "../plutus" }

tinycbor = { workspace = true }
tinycbor-derive = { workspace = true }

[dev-dependencies]
anyhow = "1"
const-hex = { workspace = true }
bs58 = "0.5"

[[test]]
name = "codec"

[[test]]
name = "cbor_len"
